#include "ekeyboardmode.h"

#define E2STR(x) #x

const QString sTMMode[]  =
{
        E2STR(TM_MODE_XFORM_ALL),
        E2STR(TM_MODE_XFORM_TILING),
        E2STR(TM_MODE_XFORM_UNIQUE_TILE),
        E2STR(TM_MODE_XFORM_PLACED_TILE),
};

const QString sLegacyMode [] =
{
        E2STR(LEGACY_MODE_DES_POS),
        E2STR(LEGACY_MODE_DES_LAYER_SELECT),
        E2STR(LEGACY_MODE_DES_ZLEVEL),
        E2STR(LEGACY_MODE_DES_STEP),
        E2STR(LEGACY_MODE_MODE_DES_SEPARATION),
        E2STR(LEGACY_MODE_DES_ORIGIN),
        E2STR(LEGACY_MODE_DES_OFFSET),
};
