#pragma once
#ifndef EKEYBOARDMODE_H
#define EKEYBOARDMODE_H

#include <QString>

extern const QString sTMMode[];
extern const QString sLegacyMode[];

enum eTMMode
{
    TM_MODE_XFORM_ALL,
    TM_MODE_XFORM_TILING,
    TM_MODE_XFORM_UNIQUE_TILE,
    TM_MODE_XFORM_PLACED_TILE
};

enum eLegacyMode
{
    LEGACY_MODE_DES_POS,
    LEGACY_MODE_DES_LAYER_SELECT,
    LEGACY_MODE_DES_ZLEVEL,
    LEGACY_MODE_DES_STEP,
    LEGACY_MODE_MODE_DES_SEPARATION,
    LEGACY_MODE_DES_ORIGIN,
    LEGACY_MODE_DES_OFFSET
};

#endif // EKEYBOARDMODE_H
