#pragma once
#ifndef ERENDER_H
#define ERENDER_H

enum eRenderType
{
    RENDER_RESET_MOTIFS,
    RENDER_RESET_ALL = RENDER_RESET_MOTIFS,
    RENDER_RESET_PROTOTYPES,
    RENDER_RESET_STYLES
};

#endif
