#include "estatemachineevent.h"

#define E2STR(x) #x

const QString sTILM_Events[] =
{
    E2STR(TILM_LOAD_EMPTY),
    E2STR(TILM_LOAD_FROM_MOSAIC),
    E2STR(TILM_LOAD_SINGLE),
    E2STR(TILM_LOAD_MULTI),
    E2STR(TILM_LOAD_REPLACE),
    E2STR(TILM_REPLACE_ALL),
    E2STR(TILM_RELOAD),
    E2STR(TILM_LOAD_FROM_STEPPER),
    E2STR(TILM_UNLOAD_TILING)
};

const QString sPROM_Events[] =
{
    E2STR(PROM_LOAD_EMPTY),
    E2STR(PROM_LOAD_SINGLE),
    E2STR(PROM_LOAD_MULTI),
    E2STR(PROM_RELOAD_SINGLE),
    E2STR(PROM_RELOAD_MULTI),
    E2STR(PROM_REPLACE),
    E2STR(PROM_REPLACE_ALL),
    E2STR(PROM_TILING_DELETED),
    E2STR(PROM_TILING_CHANGED),
    E2STR(PROM_TILING_MODIFED),
    E2STR(PROM_TILE_UNIQUE_TRANS_CHANGED),
    E2STR(PROM_TILE_UNIQUE_NATURE_CHANGED),
    E2STR(PROM_TILE_UNIQUE_REGULARITY_CHANGED),
    E2STR(PROM_TILE_PLACED_TRANS_CHANGED),
    E2STR(PROM_TILING_UNIT_CHANGED),
    E2STR(PROM_MOTIF_CHANGED),
};

const QString sMOSM_Events[] =
{
    E2STR(MOSM_LOAD_PROTO_EMPTY),
    E2STR(MOSM_LOAD_PROTO_SINGLE),
    E2STR(MOSM_LOAD_PROTO_MULTI),
    E2STR(MOSM_RELOAD_PROTO_SINGLE),
    E2STR(MOSM_RELOAD_PROTO_MULTI),
    E2STR(MOSM_PROTO_DELETED),
    E2STR(MOSM_PROTO_CHANGED)
};
