#include "etilingmaker.h"

#define E2STR(x) #x

const QString sTilingMakerMouseMode[] =
{
        E2STR(TM_NO_MOUSE_MODE),
        E2STR(TM_COPY_MODE),
        E2STR(TM_DELETE_MODE),
        E2STR(TM_TRANSLATION_VECTOR_MODE),
        E2STR(TM_DRAW_POLY_MODE),
        E2STR(TM_INCLUSION_MODE),
        E2STR(TM_POSITION_MODE),
        E2STR(TM_MEASURE_MODE),
        E2STR(TM_EDIT_TILE_MODE),
        E2STR(TM_EDGE_CURVE_MODE),
        E2STR(TM_MIRROR_X_MODE),
        E2STR(TM_MIRROR_Y_MODE),
        E2STR(TM_CONSTRUCTION_LINES),
        E2STR(TM_REFLECT_EDGE),
        E2STR(TM_UNIQUIFY_MODE),
        E2STR(TM_UNIFY_MODE),
        E2STR(TM_DECOMPOSE_MODE),
};
