#include "ecyclemode.h"

#define E2STR(x) #x

const  QString sCycleMode[] =
{
    E2STR(CYCLE_NONE),
    E2STR(CYCLE_MOSAICS),
    E2STR(CYCLE_TILINGS),
    E2STR(CYCLE_ORIGINAL_PNGS),
    E2STR(CYCLE_SAVE_MOSAIC_BMPS),
    E2STR(CYCLE_SAVE_TILING_BMPS),
    E2STR(CYCLE_COMPARE_ALL_BMPS),
    E2STR(CYCLE_COMPARE_WORKLIST_BMPS)
};
