#include "ecyclemode.h"

#define E2STR(x) #x

const  QString sCycleMode[] =
{
    E2STR(CYCLE_NONE),
    E2STR(CYCLE_STYLES),
    E2STR(CYCLE_TILINGS),
    E2STR(CYCLE_ORIGINAL_PNGS),
    E2STR(CYCLE_SAVE_STYLE_BMPS),
    E2STR(CYCLE_SAVE_TILING_BMPS),
    E2STR(CYCLE_COMPARE_ALL_IMAGES),
    E2STR(CYCLE_COMPARE_WORKLIST_IMAGES)
};
