#ifndef ECYCLEMODE_H
#define ECYCLEMODE_H

#include <QString>

extern const  QString sCycleMode[];

enum eCycleMode
{
    CYCLE_NONE,
    CYCLE_STYLES,
    CYCLE_MIN = CYCLE_STYLES,
    CYCLE_TILINGS,
    CYCLE_ORIGINAL_PNGS,
    CYCLE_SAVE_STYLE_BMPS,
    CYCLE_SAVE_TILING_BMPS,
    CYCLE_MAX = CYCLE_SAVE_TILING_BMPS,
    CYCLE_COMPARE_ALL_IMAGES,
    CYCLE_COMPARE_WORKLIST_IMAGES
};

#endif // ECYCLEMODE_H
