#ifndef EFIGTYPE_H
#define EFIGTYPE_H

#include <QString>

extern const QString sFigType[];

// these are the types of figure which can be made
enum eFigType
{
    FIG_TYPE_UNDEFINED,
    FIG_TYPE_RADIAL,
    FIG_TYPE_ROSETTE,
    FIG_TYPE_STAR,
    FIG_TYPE_CONNECT_STAR,
    FIG_TYPE_CONNECT_ROSETTE,
    FIG_TYPE_EXTENDED_ROSETTE,
    FIG_TYPE_EXTENDED_STAR,
    FIG_TYPE_EXPLICIT,
    FIG_TYPE_EXPLICIT_INFER,
    FIG_TYPE_EXPLICIT_ROSETTE,
    FIG_TYPE_EXPLICIT_HOURGLASS,
    FIG_TYPE_EXPLICIT_INTERSECT,
    FIG_TYPE_EXPLICIT_GIRIH,
    FIG_TYPE_EXPLICIT_STAR,
    FIG_TYPE_EXPLICIT_FEATURE
};

#endif // EFIGTYPE_H
