#include "efigtype.h"

#define E2STR(x) #x

const QString sFigType[] =
{
        E2STR(FIG_TYPE_UNDEFINED),
        E2STR(FIG_TYPE_RADIAL),
        E2STR(FIG_TYPE_ROSETTE),
        E2STR(FIG_TYPE_STAR),
        E2STR(FIG_TYPE_CONNECT_STAR),
        E2STR(FIG_TYPE_CONNECT_ROSETTE),
        E2STR(FIG_TYPE_EXTENDED_ROSETTE),
        E2STR(FIG_TYPE_EXTENDED_STAR),
        E2STR(FIG_TYPE_EXPLICIT),
        E2STR(FIG_TYPE_EXPLICIT_INFER),
        E2STR(FIG_TYPE_EXPLICIT_ROSETTE),
        E2STR(FIG_TYPE_EXPLICIT_HOURGLASS),
        E2STR(FIG_TYPE_EXPLICIT_INTERSECT),
        E2STR(FIG_TYPE_EXPLICIT_GIRIH),
        E2STR(FIG_TYPE_EXPLICIT_STAR),
        E2STR(FIG_TYPE_EXPLICIT_FEATURE)
};
