#include "ekeyboardmode.h"

#define E2STR(x) #x

const QString sKbdMode[]  =
{
        E2STR(KBD_MODE_XFORM_VIEW),
        E2STR(KBD_MODE_XFORM_SELECTED),
        E2STR(KBD_MODE_XFORM_BKGD),
        E2STR(KBD_MODE_XFORM_TILING),
        E2STR(KBD_MODE_XFORM_UNIQUE_TILE),
        E2STR(KBD_MODE_XFORM_PLACED_TILE),
        E2STR(KBD_MODE_XFORM_GRID),
        E2STR(KBD_MODE_DES_POS),
        E2STR(KBD_MODE_DES_LAYER_SELECT),
        E2STR(KBD_MODE_DES_ZLEVEL),
        E2STR(KBD_MODE_DES_STEP),
        E2STR(KBD_MODE_DES_SEPARATION),
        E2STR(KBD_MODE_DES_ORIGIN),
        E2STR(KBD_MODE_DES_OFFSET),
};
