#ifndef EMOTIFTYPE_H
#define EMOTIFTYPE_H

#include <QString>

extern const QString sTileType[];

// these are the types of figure which can be made
enum eMotifType
{
    MOTIF_TYPE_UNDEFINED,
    MOTIF_TYPE_RADIAL,
    MOTIF_TYPE_ROSETTE,
    MOTIF_TYPE_STAR,
    MOTIF_TYPE_CONNECT_STAR,
    MOTIF_TYPE_CONNECT_ROSETTE,
    MOTIF_TYPE_EXTENDED_ROSETTE,
    MOTIF_TYPE_EXTENDED_STAR,
    MOTIF_TYPE_EXPLICIT,
    MOTIF_TYPE_EXPLICIT_INFER,
    MOTIF_TYPE_EXPLICIT_ROSETTE,
    MOTIF_TYPE_EXPLICIT_HOURGLASS,
    MOTIF_TYPE_EXPLICIT_INTERSECT,
    MOTIF_TYPE_EXPLICIT_GIRIH,
    MOTIF_TYPE_EXPLICIT_STAR,
    MOTIF_TYPE_EXPLICIT_TILE
};

#endif // EMOTIFTYPE_H
