#include "emotiftype.h"

#define E2STR(x) #x

const QString sTileType[] =
{
        E2STR(MOTIF_TYPE_UNDEFINED),
        E2STR(MOTIF_TYPE_RADIAL),
        E2STR(MOTIF_TYPE_ROSETTE),
        E2STR(MOTIF_TYPE_STAR),
        E2STR(MOTIF_TYPE_CONNECT_STAR),
        E2STR(MOTIF_TYPE_CONNECT_ROSETTE),
        E2STR(MOTIF_TYPE_EXTENDED_ROSETTE),
        E2STR(MOTIF_TYPE_EXTENDED_STAR),
        E2STR(MOTIF_TYPE_EXPLICIT),
        E2STR(MOTIF_TYPE_EXPLICIT_INFER),
        E2STR(MOTIF_TYPE_EXPLICIT_ROSETTE),
        E2STR(MOTIF_TYPE_EXPLICIT_HOURGLASS),
        E2STR(MOTIF_TYPE_EXPLICIT_INTERSECT),
        E2STR(MOTIF_TYPE_EXPLICIT_GIRIH),
        E2STR(MOTIF_TYPE_EXPLICIT_STAR),
        E2STR(MOTIF_TYPE_EXPLICIT_TILE)
};
