#include "emotiftype.h"

#define E2STR(x) #x

const QString sMotifType[] =
{
        E2STR(MOTIF_TYPE_UNDEFINED),
        E2STR(MOTIF_TYPE_RADIAL),
        E2STR(MOTIF_TYPE_ROSETTE),
        E2STR(MOTIF_TYPE_STAR),
        E2STR(MOTIF_TYPE_CONNECT_STAR),
        E2STR(MOTIF_TYPE_CONNECT_ROSETTE),
        E2STR(MOTIF_TYPE_EXTENDED_ROSETTE),
        E2STR(MOTIF_TYPE_EXTENDED_STAR),
        E2STR(MOTIF_TYPE_EXPLICIT_MAP),
        E2STR(MOTIF_TYPE_INFERRED),
        E2STR(MOTIF_TYPE_IRREGULAR_ROSETTE),
        E2STR(MOTIF_TYPE_HOURGLASS),
        E2STR(MOTIF_TYPE_INTERSECT),
        E2STR(MOTIF_TYPE_GIRIH),
        E2STR(MOTIF_TYPE_IRREGULAR_STAR),
        E2STR(MOTIF_TYPE_EXPLCIT_TILE),
        E2STR(MOTIF_TYPE_IRREGULAR_NO_MAP)
};
