#ifndef EMOUSEMODE_H
#define EMOUSEMODE_H

enum eMouseMode
{
    MOUSE_MODE_NONE,
    MOUSE_MODE_TRANSLATE,
    MOUSE_MODE_ROTATE,
    MOUSE_MODE_SCALE,
    MOUSE_MODE_CENTER,
};

#endif // EMOUSEMODE_H
