#ifndef EPANELPAGE_H
#define EPANELPAGE_H

enum ePanelPage
{
PAGE_LOAD,
PAGE_SAVE,
PAGE_MOSIAC_MAKER,
PAGE_MOTIF_MAKER,
PAGE_TILING_MAKER,
PAGE_BORDER_MAKER,
PAGE_CROP_MAKER,
PAGE_BKGD_MAKER,
PAGE_MODEL_SETTINGS,
PAGE_GRID,
PAGE_MAP_EDITOR,
PAGE_MOSAIC_INFO,
PAGE_PROTO_INFO,
PAGE_LAYER_INFO,
PAGE_SYSTEM_INFO,
PAGE_CONFIG,
PAGE_IMAGE_TOOLS,
PAGE_DEBUG_TOOLS,
PAGE_LOG
};

#endif // EPANELPAGE_H
