#ifndef ETILINGMAKERMOUSEMODE_H
#define ETILINGMAKERMOUSEMODE_H

#include <QString>

extern const QString sTilingMakerMouseMode[];

enum eTilingMakerMouseMode
{
    TM_NO_MOUSE_MODE,
    TM_COPY_MODE,
    TM_DELETE_MODE,
    TM_TRANSLATION_VECTOR_MODE,
    TM_DRAW_POLY_MODE,
    TM_INCLUSION_MODE,
    TM_POSITION_MODE,
    TM_MEASURE_MODE,
    TM_EDIT_FEATURE_MODE,
    TM_EDGE_CURVE_MODE,
    TM_MIRROR_X_MODE,
    TM_MIRROR_Y_MODE,
    TM_CONSTRUCTION_LINES
};

#endif // ETILINGMAKERMOUSEMODE_H
